export interface ExecutiveProps {
  id: string | number
  name: string
  position: string
  term: string
  image?: string
  email?: string
  linkedIn?: string
  bio?: string
  achievements?: string[]
  phone?: string
  location?: string
  website?: string
}

export const currentExecutives: ExecutiveProps[] = [
  {
    id: "current-1",
    name: "Dr. Thomas Wilson",
    position: "President",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "thomas.wilson@example.com",
    linkedIn: "https://linkedin.com/in/thomaswilson",
    phone: "+234 803 123 4567",
    location: "Lagos, Nigeria",
    website: "https://thomaswilson.com",
    bio: "A distinguished cardiologist with over 20 years of experience in healthcare leadership. Thomas has been instrumental in establishing our scholarship programs and community outreach initiatives. He completed his medical degree at the University of Lagos and specialized in cardiology at Johns Hopkins University. His passion for education and community development has driven many of our association's most successful programs.",
    achievements: [
      "Established the annual scholarship fund worth ₦50 million",
      "Led the alumni center construction project valued at ₦200 million",
      "Increased membership by 40% during tenure",
      "Organized 5 successful medical outreach programs",
      "Secured partnerships with 3 major hospitals for student internships",
      "Launched the emergency medical fund for alumni",
    ],
  },
  {
    id: "current-2",
    name: "Prof. Elizabeth Taylor",
    position: "Vice President",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "elizabeth.taylor@example.com",
    linkedIn: "https://linkedin.com/in/elizabethtaylor",
    phone: "+234 806 987 6543",
    location: "Abuja, Nigeria",
    website: "https://elizabethtaylor-economics.com",
    bio: "An award-winning professor of Economics and public policy advisor. Elizabeth leads our mentorship initiatives and academic outreach programs. She holds a PhD in Economics from Harvard University and has published over 50 research papers. Her expertise in economic policy has been instrumental in shaping our association's strategic direction.",
    achievements: [
      "Launched the mentorship program connecting 200+ students with professionals",
      "Secured partnerships with 5 universities for academic exchange programs",
      "Published research on alumni engagement best practices",
      "Established the academic excellence scholarship program",
      "Organized 3 international conferences on education and development",
    ],
  },
  {
    id: "current-3",
    name: "Richard Anderson",
    position: "Secretary",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "richard.anderson@example.com",
    linkedIn: "https://linkedin.com/in/richardanderson",
    phone: "+234 805 456 7890",
    location: "Port Harcourt, Nigeria",
    bio: "A corporate lawyer specializing in international business. Richard manages our alumni communications and documentation with exceptional attention to detail. He graduated from the Nigerian Law School and has an LLM from Oxford University. His legal expertise has been crucial in structuring our association's governance framework.",
    achievements: [
      "Digitized all alumni records spanning 35 years",
      "Implemented new communication systems reaching 95% of members",
      "Organized 3 successful reunions with record attendance",
      "Established the legal aid fund for alumni",
      "Created the association's first mobile app",
    ],
  },
  {
    id: "current-4",
    name: "Patricia Martin",
    position: "Treasurer",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "patricia.martin@example.com",
    linkedIn: "https://linkedin.com/in/patriciamartin",
    phone: "+234 807 234 5678",
    location: "Kano, Nigeria",
    bio: "A certified financial analyst and investment banker. Patricia oversees our financial planning and ensures transparent management of our resources. She holds an MBA in Finance from INSEAD and has over 15 years of experience in investment banking. Her financial acumen has significantly strengthened our association's fiscal position.",
    achievements: [
      "Increased endowment fund by 200% to ₦500 million",
      "Implemented transparent financial reporting systems",
      "Secured major corporate sponsorships worth ₦100 million",
      "Established investment portfolio generating 15% annual returns",
      "Created financial literacy programs for members",
    ],
  },
  {
    id: "current-5",
    name: "Dr. Michael Chen",
    position: "Public Relations Officer",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "michael.chen@example.com",
    linkedIn: "https://linkedin.com/in/michaelchen",
    phone: "+234 809 876 5432",
    location: "Ibadan, Nigeria",
    bio: "A renowned surgeon and medical researcher. Michael handles our public relations and media communications. He completed his medical training at the University of Ibadan and has a fellowship in surgery from the Royal College of Surgeons. His media presence has significantly raised the profile of our association.",
    achievements: [
      "Increased social media following by 300% across all platforms",
      "Secured media coverage for major events in 15+ publications",
      "Launched alumni newsletter reaching 5,000+ subscribers",
      "Organized press conferences for major announcements",
      "Established media partnerships with 5 major news outlets",
    ],
  },
  {
    id: "current-6",
    name: "Sarah Johnson",
    position: "Welfare Officer",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "sarah.johnson@example.com",
    linkedIn: "https://linkedin.com/in/sarahjohnson",
    phone: "+234 808 345 6789",
    location: "Enugu, Nigeria",
    bio: "A social worker and community development specialist. Sarah coordinates our welfare programs and member support initiatives. She has a Master's degree in Social Work from the University of Nigeria, Nsukka, and has dedicated her career to community development and social welfare programs.",
    achievements: [
      "Established emergency support fund helping 50+ families",
      "Coordinated health insurance program covering 80% of members",
      "Organized wellness workshops attended by 500+ participants",
      "Created bereavement support system for grieving families",
      "Launched mental health awareness campaigns",
    ],
  },
  {
    id: "current-7",
    name: "James Okafor",
    position: "Projects Coordinator",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "james.okafor@example.com",
    linkedIn: "https://linkedin.com/in/jamesokafor",
    phone: "+234 806 123 4567",
    location: "Owerri, Nigeria",
    bio: "An engineer and project management expert. James oversees all our development projects and infrastructure initiatives. He holds a degree in Civil Engineering from the University of Nigeria, Nsukka, and is a certified Project Management Professional (PMP). His engineering expertise has been vital in our infrastructure development projects.",
    achievements: [
      "Completed library renovation project worth ₦80 million",
      "Managed science lab upgrade benefiting 1,000+ students",
      "Led community water project serving 5,000 residents",
      "Supervised construction of new classroom blocks",
      "Implemented solar power systems in 3 school buildings",
    ],
  },
  {
    id: "current-8",
    name: "Grace Adebayo",
    position: "Social Secretary",
    term: "2023-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "grace.adebayo@example.com",
    linkedIn: "https://linkedin.com/in/graceadebayo",
    phone: "+234 807 987 6543",
    location: "Kaduna, Nigeria",
    bio: "An event management professional and hospitality expert. Grace coordinates all our social events and networking activities. She has a degree in Hospitality Management and over 10 years of experience in event planning. Her creativity and attention to detail have made our events memorable and well-attended.",
    achievements: [
      "Organized 5 successful networking events with 500+ attendees each",
      "Increased event attendance by 60% through innovative planning",
      "Launched annual gala dinner raising ₦30 million for scholarships",
      "Created virtual event platform during COVID-19 pandemic",
      "Established partnerships with premium venues for member discounts",
    ],
  },
]

export const pastExecutives: ExecutiveProps[] = [
  // 2021-2023 Term
  {
    id: "past-1",
    name: "Dr. Robert Nkomo",
    position: "President",
    term: "2021-2023",
    image: "/placeholder.svg?height=400&width=300",
    email: "robert.nkomo@example.com",
    linkedIn: "https://linkedin.com/in/robertnkomo",
    phone: "+234 803 111 2222",
    location: "Lagos, Nigeria",
    bio: "Former president who led the association through the challenging COVID-19 period, implementing virtual engagement strategies. Dr. Nkomo is a cardiologist with extensive experience in healthcare administration. His leadership during the pandemic ensured continuity of our programs and maintained strong member engagement despite physical distancing requirements.",
    achievements: [
      "Transitioned to virtual events during pandemic maintaining 95% member engagement",
      "Launched online mentorship platform connecting 150+ mentor-mentee pairs",
      "Established COVID-19 relief fund supporting 100+ affected families",
      "Organized virtual graduation ceremony for 2020 and 2021 classes",
      "Implemented digital payment systems for all association transactions",
      "Created online resource library with 500+ educational materials",
    ],
  },
  {
    id: "past-2",
    name: "Dr. Mary Eze",
    position: "Vice President",
    term: "2021-2023",
    image: "/placeholder.svg?height=400&width=300",
    email: "mary.eze@example.com",
    linkedIn: "https://linkedin.com/in/maryeze",
    phone: "+234 806 333 4444",
    location: "Abuja, Nigeria",
    bio: "A pediatrician who focused on healthcare initiatives and student welfare programs during her tenure. Dr. Eze has dedicated her career to child healthcare and has been instrumental in establishing health programs for students and community members.",
    achievements: [
      "Established student health clinic serving 2,000+ students annually",
      "Organized medical outreach programs reaching 10,000+ community members",
      "Created health scholarship fund supporting 25 medical students",
      "Launched vaccination campaigns in rural communities",
      "Established partnerships with 5 major hospitals for student placements",
    ],
  },
  {
    id: "past-3",
    name: "Engineer Paul Okoro",
    position: "Secretary",
    term: "2021-2023",
    image: "/placeholder.svg?height=400&width=300",
    email: "paul.okoro@example.com",
    linkedIn: "https://linkedin.com/in/paulokoro",
    phone: "+234 805 555 6666",
    location: "Port Harcourt, Nigeria",
    bio: "A civil engineer who modernized the association's record-keeping and communication systems. Engineer Okoro brought his technical expertise to streamline operations and improve efficiency in all administrative processes.",
    achievements: [
      "Developed comprehensive alumni database system with 10,000+ records",
      "Created digital archive of school history spanning 50 years",
      "Improved communication efficiency by 80% through automation",
      "Implemented cloud-based document management system",
      "Established IT support team for technical assistance",
    ],
  },
  {
    id: "past-4",
    name: "Mrs. Helen Udoh",
    position: "Treasurer",
    term: "2021-2023",
    image: "/placeholder.svg?height=400&width=300",
    email: "helen.udoh@example.com",
    linkedIn: "https://linkedin.com/in/helenudoh",
    phone: "+234 807 777 8888",
    location: "Calabar, Nigeria",
    bio: "An accountant who established robust financial management systems and transparency protocols. Mrs. Udoh's expertise in financial management has been crucial in building trust and ensuring accountability in the association's financial operations.",
    achievements: [
      "Implemented quarterly financial reports with 100% transparency",
      "Established independent audit committee ensuring accountability",
      "Increased reserve funds by 150% through strategic investments",
      "Created financial planning workshops for members",
      "Established emergency fund protocols for crisis management",
    ],
  },

  // 2019-2021 Term
  {
    id: "past-5",
    name: "Prof. David Akpan",
    position: "President",
    term: "2019-2021",
    image: "/placeholder.svg?height=400&width=300",
    email: "david.akpan@example.com",
    linkedIn: "https://linkedin.com/in/davidakpan",
    phone: "+234 809 999 0000",
    location: "Uyo, Nigeria",
    bio: "A university professor who emphasized educational excellence and academic partnerships. Prof. Akpan has spent over 25 years in academia and has been instrumental in forging partnerships between our association and various educational institutions.",
    achievements: [
      "Established university partnership program with 8 institutions",
      "Created academic excellence awards recognizing top performers",
      "Launched teacher training initiative benefiting 200+ educators",
      "Secured research grants worth ₦75 million for educational projects",
      "Organized international education conference with 500+ participants",
    ],
  },
  {
    id: "past-6",
    name: "Dr. Grace Etim",
    position: "Vice President",
    term: "2019-2021",
    image: "/placeholder.svg?height=400&width=300",
    email: "grace.etim@example.com",
    linkedIn: "https://linkedin.com/in/graceetim",
    phone: "+234 808 111 2222",
    location: "Uyo, Nigeria",
    bio: "A medical doctor who focused on healthcare and wellness programs for alumni and students. Dr. Etim has been a strong advocate for preventive healthcare and has implemented numerous health awareness programs.",
    achievements: [
      "Organized annual health screening programs for 1,000+ participants",
      "Established wellness committee promoting healthy lifestyles",
      "Created health awareness campaigns reaching 5,000+ people",
      "Launched diabetes and hypertension prevention programs",
      "Established partnerships with health insurance companies",
    ],
  },

  // Additional past executives with enhanced data
  {
    id: "past-7",
    name: "Mr. John Bassey",
    position: "Secretary",
    term: "2019-2021",
    image: "/placeholder.svg?height=400&width=300",
    email: "john.bassey@example.com",
    linkedIn: "https://linkedin.com/in/johnbassey",
    phone: "+234 806 333 4444",
    location: "Calabar, Nigeria",
    bio: "A business executive who streamlined administrative processes and improved member services. Mr. Bassey brought corporate efficiency to the association's operations.",
    achievements: [
      "Reduced processing time by 60% through process optimization",
      "Implemented member portal serving 3,000+ active users",
      "Created standard operating procedures for all departments",
      "Established customer service standards improving satisfaction by 85%",
    ],
  },
  {
    id: "past-8",
    name: "Mrs. Rose Inyang",
    position: "Treasurer",
    term: "2019-2021",
    image: "/placeholder.svg?height=400&width=300",
    email: "rose.inyang@example.com",
    linkedIn: "https://linkedin.com/in/roseinyang",
    phone: "+234 805 555 6666",
    location: "Uyo, Nigeria",
    bio: "A financial consultant who established the foundation for the association's current financial strength. Mrs. Inyang's strategic financial planning has been instrumental in building our current financial position.",
    achievements: [
      "Created diversified investment portfolio generating consistent returns",
      "Established financial planning committee with expert advisors",
      "Increased revenue streams by 120% through strategic initiatives",
      "Implemented cost-saving measures reducing expenses by 30%",
    ],
  },

  // Continue with more past executives...
  {
    id: "past-9",
    name: "Dr. Samuel Okon",
    position: "President",
    term: "2017-2019",
    image: "/placeholder.svg?height=400&width=300",
    email: "samuel.okon@example.com",
    linkedIn: "https://linkedin.com/in/samuelokon",
    phone: "+234 807 777 8888",
    location: "Akwa Ibom, Nigeria",
    bio: "A veterinarian who led major infrastructure development projects at the school. Dr. Okon's leadership resulted in significant improvements to the school's physical infrastructure.",
    achievements: [
      "Completed dormitory renovation project housing 500+ students",
      "Established modern computer laboratory with 100+ workstations",
      "Created agricultural development program supporting local farmers",
      "Built new sports complex with modern facilities",
    ],
  },
  {
    id: "past-10",
    name: "Mrs. Joy Essien",
    position: "Vice President",
    term: "2017-2019",
    image: "/placeholder.svg?height=400&width=300",
    email: "joy.essien@example.com",
    linkedIn: "https://linkedin.com/in/joyessien",
    phone: "+234 809 999 0000",
    location: "Akwa Ibom, Nigeria",
    bio: "An educator who focused on curriculum development and teacher support programs. Mrs. Essien has been passionate about improving educational standards and teacher welfare.",
    achievements: [
      "Launched teacher mentorship program supporting 150+ educators",
      "Provided educational materials worth ₦20 million to schools",
      "Organized curriculum development workshops for 200+ teachers",
      "Established teacher welfare fund supporting professional development",
    ],
  },
]
