export interface TrusteeProps {
  id: string | number
  name: string
  position: string
  term: string
  image?: string
  email?: string
  linkedIn?: string
  bio?: string
  achievements?: string[]
  phone?: string
  location?: string
  website?: string
}

export const currentTrustees: TrusteeProps[] = [
  {
    id: "current-1",
    name: "Prof. Margaret Akpabio",
    position: "Chairperson",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "margaret.akpabio@example.com",
    linkedIn: "https://linkedin.com/in/margaretakpabio",
    phone: "+234 803 111 2222",
    location: "Abuja, Nigeria",
    website: "https://margaretakpabio.com",
    bio: "A distinguished professor of Education and former Vice-Chancellor with over 30 years of experience in academic leadership. Prof. Akpabio has been instrumental in shaping educational policy in Nigeria and has served on numerous national education committees. Her vision for alumni engagement and institutional development has guided our association's strategic direction.",
    achievements: [
      "Led the establishment of the ₦1 billion endowment fund",
      "Secured partnerships with 10 international universities",
      "Oversaw the construction of the alumni center worth ₦500 million",
      "Implemented governance reforms improving transparency by 95%",
      "Launched the global alumni network spanning 25 countries",
      "Established the annual leadership summit attracting 1,000+ participants",
    ],
  },
  {
    id: "current-2",
    name: "Dr. Emmanuel Udo",
    position: "Vice Chairperson",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "emmanuel.udo@example.com",
    linkedIn: "https://linkedin.com/in/emmanueludo",
    phone: "+234 806 333 4444",
    location: "Lagos, Nigeria",
    website: "https://emmanueludo-medical.com",
    bio: "A renowned cardiologist and healthcare administrator with extensive experience in medical leadership. Dr. Udo has served as Chief Medical Director of several leading hospitals and has been a pioneer in telemedicine in Nigeria. His expertise in strategic planning and healthcare management has been invaluable to our board.",
    achievements: [
      "Established the medical scholarship program supporting 100+ students",
      "Led healthcare initiatives reaching 50,000+ community members",
      "Secured ₦200 million in healthcare grants for rural communities",
      "Implemented telemedicine programs in 15 rural health centers",
      "Organized annual medical missions benefiting 10,000+ patients",
    ],
  },
  {
    id: "current-3",
    name: "Chief Comfort Obot",
    position: "Secretary",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "comfort.obot@example.com",
    linkedIn: "https://linkedin.com/in/comfortobot",
    phone: "+234 805 555 6666",
    location: "Port Harcourt, Nigeria",
    bio: "A distinguished lawyer and former Attorney General with expertise in corporate governance and legal affairs. Chief Obot has been instrumental in establishing the legal framework for our association's operations and ensuring compliance with regulatory requirements.",
    achievements: [
      "Drafted comprehensive governance policies and procedures",
      "Established legal aid fund supporting 200+ alumni",
      "Led constitutional review process improving organizational structure",
      "Secured legal recognition for international chapters",
      "Implemented compliance frameworks meeting international standards",
    ],
  },
  {
    id: "current-4",
    name: "Engr. Moses Udom",
    position: "Treasurer",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "moses.udom@example.com",
    linkedIn: "https://linkedin.com/in/mosesudom",
    phone: "+234 807 777 8888",
    location: "Uyo, Nigeria",
    bio: "A structural engineer and financial expert with extensive experience in project management and financial planning. Engr. Udom has overseen major infrastructure projects worth billions of naira and brings his expertise to ensure sound financial management of our association's resources.",
    achievements: [
      "Increased association reserves by 400% through strategic investments",
      "Implemented robust financial management systems",
      "Secured ₦300 million in infrastructure funding",
      "Established transparent audit procedures",
      "Created sustainable revenue streams generating ₦50 million annually",
    ],
  },
  {
    id: "current-5",
    name: "Dr. Faith Umoh",
    position: "Member",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "faith.umoh@example.com",
    linkedIn: "https://linkedin.com/in/faithumoh",
    phone: "+234 809 999 0000",
    location: "Calabar, Nigeria",
    bio: "A pharmacist and public health expert with extensive experience in healthcare policy and community development. Dr. Umoh has been a strong advocate for healthcare access and has led numerous public health initiatives across Nigeria.",
    achievements: [
      "Established community health programs in 20 rural areas",
      "Led pharmaceutical outreach programs distributing ₦100 million in medicines",
      "Created health education curricula for secondary schools",
      "Organized health screening programs for 25,000+ individuals",
      "Secured partnerships with international health organizations",
    ],
  },
  {
    id: "current-6",
    name: "Prof. Daniel Ekanem",
    position: "Member",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "daniel.ekanem@example.com",
    linkedIn: "https://linkedin.com/in/danielekanem",
    phone: "+234 808 111 2222",
    location: "Ibadan, Nigeria",
    bio: "A professor of Agricultural Sciences and former Dean of Agriculture with expertise in sustainable development and rural empowerment. Prof. Ekanem has been instrumental in developing agricultural programs that have transformed rural communities.",
    achievements: [
      "Established agricultural training centers in 10 communities",
      "Led food security initiatives benefiting 100,000+ farmers",
      "Secured ₦150 million in agricultural development grants",
      "Created sustainable farming programs increasing yields by 200%",
      "Organized annual agricultural conferences with 2,000+ participants",
    ],
  },
  {
    id: "current-7",
    name: "Mrs. Victoria Ita",
    position: "Member",
    term: "2020-2025",
    image: "/placeholder.svg?height=400&width=300",
    email: "victoria.ita@example.com",
    linkedIn: "https://linkedin.com/in/victoriaita",
    phone: "+234 806 333 4444",
    location: "Enugu, Nigeria",
    bio: "A business executive and entrepreneur with extensive experience in corporate strategy and business development. Mrs. Ita has built successful businesses across multiple sectors and brings her entrepreneurial expertise to guide our association's strategic initiatives.",
    achievements: [
      "Established business incubation programs supporting 50+ startups",
      "Created entrepreneurship training curricula for alumni",
      "Secured ₦100 million in business development funding",
      "Organized annual business summits with 1,500+ participants",
      "Established mentorship programs connecting 300+ entrepreneurs",
    ],
  },
]

export const pastTrustees: TrusteeProps[] = [
  // 2015-2020 Term
  {
    id: "past-1",
    name: "Chief Samuel Okon",
    position: "Chairperson",
    term: "2015-2020",
    image: "/placeholder.svg?height=400&width=300",
    email: "samuel.okon@example.com",
    linkedIn: "https://linkedin.com/in/samuelokon",
    phone: "+234 803 111 2222",
    location: "Lagos, Nigeria",
    bio: "Former chairperson who led the association through a period of significant growth and modernization. Chief Okon's leadership resulted in the establishment of many of our current programs and the expansion of our global reach.",
    achievements: [
      "Established the first international alumni chapters",
      "Led the digital transformation initiative",
      "Secured major corporate partnerships worth ₦500 million",
      "Implemented modern governance structures",
      "Launched the annual alumni conference",
      "Created the alumni database system",
    ],
  },
  {
    id: "past-2",
    name: "Dr. Grace Etim",
    position: "Vice Chairperson",
    term: "2015-2020",
    image: "/placeholder.svg?height=400&width=300",
    email: "grace.etim@example.com",
    linkedIn: "https://linkedin.com/in/graceetim",
    phone: "+234 806 333 4444",
    location: "Uyo, Nigeria",
    bio: "A medical doctor who focused on healthcare initiatives and community development during her tenure as vice chairperson. Her leadership in health programs has had lasting impact on our community outreach efforts.",
    achievements: [
      "Established the first community health centers",
      "Led medical outreach programs reaching 30,000+ people",
      "Created health scholarship programs",
      "Organized annual health summits",
      "Secured partnerships with major hospitals",
    ],
  },
  {
    id: "past-3",
    name: "Barr. John Bassey",
    position: "Secretary",
    term: "2015-2020",
    image: "/placeholder.svg?height=400&width=300",
    email: "john.bassey@example.com",
    linkedIn: "https://linkedin.com/in/johnbassey",
    phone: "+234 805 555 6666",
    location: "Calabar, Nigeria",
    bio: "A legal practitioner who established the foundation for our current governance structure. His expertise in corporate law was instrumental in creating the legal framework that guides our operations today.",
    achievements: [
      "Drafted the association's constitution",
      "Established legal compliance procedures",
      "Created governance policies and procedures",
      "Secured legal recognition for the association",
      "Implemented transparency and accountability measures",
    ],
  },
  {
    id: "past-4",
    name: "Mrs. Rose Inyang",
    position: "Treasurer",
    term: "2015-2020",
    image: "/placeholder.svg?height=400&width=300",
    email: "rose.inyang@example.com",
    linkedIn: "https://linkedin.com/in/roseinyang",
    phone: "+234 807 777 8888",
    location: "Uyo, Nigeria",
    bio: "A financial consultant who established the foundation for the association's current financial strength. Mrs. Inyang's strategic financial planning was instrumental in building our current financial position and establishing sustainable revenue streams.",
    achievements: [
      "Created diversified investment portfolio generating consistent returns",
      "Established financial planning committee with expert advisors",
      "Increased revenue streams by 120% through strategic initiatives",
      "Implemented cost-saving measures reducing expenses by 30%",
      "Secured major funding for infrastructure projects",
    ],
  },

  // 2010-2015 Term
  {
    id: "past-5",
    name: "Prof. David Akpan",
    position: "Chairperson",
    term: "2010-2015",
    image: "/placeholder.svg?height=400&width=300",
    email: "david.akpan@example.com",
    linkedIn: "https://linkedin.com/in/davidakpan",
    phone: "+234 809 999 0000",
    location: "Uyo, Nigeria",
    bio: "A university professor who emphasized educational excellence and academic partnerships during his tenure as chairperson. Prof. Akpan's leadership resulted in significant improvements to educational programs and academic standards.",
    achievements: [
      "Established university partnership programs",
      "Created academic excellence awards",
      "Launched teacher training initiatives",
      "Secured research grants for educational projects",
      "Organized international education conferences",
    ],
  },
  {
    id: "past-6",
    name: "Dr. Mary Eze",
    position: "Vice Chairperson",
    term: "2010-2015",
    image: "/placeholder.svg?height=400&width=300",
    email: "mary.eze@example.com",
    linkedIn: "https://linkedin.com/in/maryeze",
    phone: "+234 808 111 2222",
    location: "Abuja, Nigeria",
    bio: "A pediatrician who focused on healthcare and wellness programs during her tenure. Dr. Eze's initiatives in child healthcare and community wellness have had lasting impact on our health programs.",
    achievements: [
      "Established pediatric care programs",
      "Created child health awareness campaigns",
      "Organized vaccination drives in rural communities",
      "Secured partnerships with international health organizations",
      "Launched maternal and child health initiatives",
    ],
  },

  // 2005-2010 Term
  {
    id: "past-7",
    name: "Chief Peter Ekong",
    position: "Chairperson",
    term: "2005-2010",
    image: "/placeholder.svg?height=400&width=300",
    email: "peter.ekong@example.com",
    linkedIn: "https://linkedin.com/in/peterekong",
    phone: "+234 806 333 4444",
    location: "Lagos, Nigeria",
    bio: "A banker and financial expert who established the association's first endowment fund and financial planning systems. Chief Ekong's financial acumen laid the foundation for our current financial stability.",
    achievements: [
      "Created the first endowment fund",
      "Established scholarship programs",
      "Implemented financial planning systems",
      "Secured major corporate sponsorships",
      "Created sustainable funding mechanisms",
    ],
  },
  {
    id: "past-8",
    name: "Mrs. Joy Essien",
    position: "Vice Chairperson",
    term: "2005-2010",
    image: "/placeholder.svg?height=400&width=300",
    email: "joy.essien@example.com",
    linkedIn: "https://linkedin.com/in/joyessien",
    phone: "+234 805 555 6666",
    location: "Akwa Ibom, Nigeria",
    bio: "An educator who focused on curriculum development and teacher support programs. Mrs. Essien's dedication to educational excellence has influenced our approach to academic support and teacher development.",
    achievements: [
      "Launched teacher mentorship programs",
      "Provided educational materials to schools",
      "Organized curriculum development workshops",
      "Established teacher welfare funds",
      "Created educational resource centers",
    ],
  },

  // 2000-2005 Term
  {
    id: "past-9",
    name: "Dr. Robert Nkomo",
    position: "Chairperson",
    term: "2000-2005",
    image: "/placeholder.svg?height=400&width=300",
    email: "robert.nkomo@example.com",
    linkedIn: "https://linkedin.com/in/robertnkomo",
    phone: "+234 807 777 8888",
    location: "Lagos, Nigeria",
    bio: "Former chairperson who led the association during its formative years, establishing many of the foundational programs and structures that continue to guide our operations today.",
    achievements: [
      "Established the formal board structure",
      "Created the first strategic plan",
      "Launched community development programs",
      "Secured initial funding for major projects",
      "Organized the first major alumni reunion",
    ],
  },
  {
    id: "past-10",
    name: "Mrs. Helen Udoh",
    position: "Treasurer",
    term: "2000-2005",
    image: "/placeholder.svg?height=400&width=300",
    email: "helen.udoh@example.com",
    linkedIn: "https://linkedin.com/in/helenudoh",
    phone: "+234 809 999 0000",
    location: "Calabar, Nigeria",
    bio: "An accountant who established the first financial management systems and transparency protocols for the association. Her work laid the foundation for our current financial accountability standards.",
    achievements: [
      "Implemented the first financial reporting systems",
      "Established audit procedures",
      "Created budget planning processes",
      "Secured initial funding for operations",
      "Established financial transparency standards",
    ],
  },

  // 1995-2000 Term
  {
    id: "past-11",
    name: "Prof. Thomas Wilson",
    position: "Chairperson",
    term: "1995-2000",
    image: "/placeholder.svg?height=400&width=300",
    email: "thomas.wilson@example.com",
    linkedIn: "https://linkedin.com/in/thomaswilson",
    phone: "+234 808 111 2222",
    location: "Ibadan, Nigeria",
    bio: "One of the founding chairpersons who helped establish the board of trustees structure. Prof. Wilson's vision and leadership were instrumental in creating the governance framework that guides our association today.",
    achievements: [
      "Co-founded the board of trustees",
      "Established governance principles",
      "Created the association's mission and vision",
      "Secured initial legal recognition",
      "Organized founding members and stakeholders",
    ],
  },
  {
    id: "past-12",
    name: "Dr. Elizabeth Taylor",
    position: "Secretary",
    term: "1995-2000",
    image: "/placeholder.svg?height=400&width=300",
    email: "elizabeth.taylor@example.com",
    linkedIn: "https://linkedin.com/in/elizabethtaylor",
    phone: "+234 806 333 4444",
    location: "Abuja, Nigeria",
    bio: "A founding member who helped establish the documentation and record-keeping systems for the board. Her meticulous approach to governance documentation has been invaluable to our institutional memory.",
    achievements: [
      "Created the first governance documents",
      "Established record-keeping systems",
      "Documented founding principles and values",
      "Created meeting procedures and protocols",
      "Established communication frameworks",
    ],
  },

  // 1990-1995 Term
  {
    id: "past-13",
    name: "Chief Emmanuel Udo",
    position: "Founding Chairperson",
    term: "1990-1995",
    image: "/placeholder.svg?height=400&width=300",
    email: "emmanuel.udo@example.com",
    linkedIn: "https://linkedin.com/in/emmanueludo",
    phone: "+234 805 555 6666",
    location: "Lagos, Nigeria",
    bio: "The founding chairperson of the board of trustees who had the vision to establish formal governance for our alumni association. His leadership and foresight created the foundation upon which our current success is built.",
    achievements: [
      "Founded the board of trustees structure",
      "Established the association's legal framework",
      "Created the first strategic vision",
      "Organized the founding board members",
      "Secured initial resources and support",
      "Laid the foundation for sustainable governance",
    ],
  },
]
